### ISSUE TITLE
Adding a Korean SLKA-25001 version to the script

### ISSUE THREAD

**Issue by Bigmanjapan** [Nisto/sh2ex#2]
Hello @Nisto

@Polymega shared an image of Silent Hill 2 Korean version. We can send you the image if you want to add it to your extraction script.

**Comment by Nisto** [comment]
@Bigmanjapan Sure, I can try to add it. Where can I find it?

**Comment by Polymega** [comment]
@Nisto I'll send you an email shortly.

**Comment by Nisto** [comment]
@Polymega @Bigmanjapan I've just added support for SLKA-25001. Let me know if there's any problem.
