### ISSUE TITLE
Support for prototype build VW047-U1

### ISSUE THREAD

**Issue by Polymega** [Nisto/sh2ex#4]
Hi Nisto, 

Hope you've been well!

If interested, could a prototype build of Silent Hill 2 be added to the extraction tool? Info and files can be found here: https://hiddenpalace.org/Silent_Hill_2_(Jul_13,_2001_prototype)

**Comment by IanSapp128** [comment]
I've been trying all morning to figure out how to get the offsets for this prototype build, comparing it to the other builds but it appears my knowledge isn't good enough :(

**Comment by CygnosOne** [comment]
I modified the code a litte, still buggy but it let you extract a lot of things (pps Files...). Still need to look more into the code.

[sh2ex_modified.zip](https://github.com/Nisto/sh2ex/files/3722645/sh2ex_modified.zip)

**Comment by Sonderhen13** [comment]
Hello @Nisto , if you could add this version in the extraction tool, I would appreciate it a lot.

**Comment by Sonderhen13** [comment]
> I modified the code a litte, still buggy but it let you extract a lot of things (pps Files...). Still need to look more into the code.
> 
> [sh2ex_modified.zip](https://github.com/Nisto/sh2ex/files/3722645/sh2ex_modified.zip)

Unfortunately several files were not extracted

**Comment by Nisto** [comment]
@Polymega @IanSapp128 @CygnosOne @Sonderhen13 Sorry for such a long delay. Life has hit me with quite a few curveballs recently, and more than a couple of roadblocks, which have limited my ability to maintain projects like these in the past couple of years. And since GitHub isn't very good with notifications, I also only noticed this issue a few weeks back. Anyway, the script has now been updated to support this prototype. If there are any specific problems, let me know.

**Comment by Polymega** [comment]
Hi Nisto,

Life certainly has its ups and downs, and I'm sorry to hear you've been hit with those curveballs as of late. The positive here, however, is you can't have downs with ups, so ups are on the way. In the meantime, thank you very much for taking the time to add further compatibility to your tool here. 

I won't have time in the near future to extensively test the prototype's compatibility with it, so I'll close the ticket under the presumption all is good. If anyone else here in this thread tests before me and finds issues, please let us know in this ticket and I can re-open it.

Thank you again, Nisto. 🙏
